[package]
name = "asciivid"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
ctrlc = "3.4.7"
image = "0.25.6"
imageproc = "0.25.0"
rayon = "1.10.0"
regex = "1.11.1"
rusttype = "0.9.3"
ab_glyph = "0.2"